### ISSUE TITLE
Example could be useful

### ISSUE THREAD

**Issue by marekolszewski** [YsnKsy/react-native-geth#3]
Hi @YsnKsy,

Thanks for putting this library together. Do you have an example of it in action? I played around a little but my import seems to always return undefined.

Thanks!

M.

**Comment by marekolszewski** [comment]
On the import side, I was able to fix my issues with #4.

**Comment by YsnKsy** [comment]
Hi @marekolszewski,

I'll put an example as soon as possible!
Can you put your last PR on the Develop branch?

Thanks :)

**Comment by marekolszewski** [comment]
@YsnKsy Just moved the PR over.

**Comment by YsnKsy** [comment]
@marekolszewski 

Voila => [Example](https://github.com/YsnKsy/react-native-geth/blob/master/README.md)

**Comment by marekolszewski** [comment]
Thanks! Really helpful.
